services:
  app:
    image: ${DOCKER_IMAGE:-catxi-backend:latest}
    container_name: catxi-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    networks:
      - catxi-network

networks:
  catxi-network:
    driver: bridge