spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/catxi?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&connectionTimeZone=Asia/Seoul&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 연결 풀 크기 설정
      maximum-pool-size: 20
      minimum-idle: 5
      # 연결 타임아웃 설정
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      # 연결 검증 설정
      validation-timeout: 5000
      connection-test-query: SELECT 1
      # 누수 감지 설정
      leak-detection-threshold: 60000
      # 자동 커밋 설정
      auto-commit: true
      # 연결 초기화 실패 시 빠른 실패
      initialization-fail-timeout: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jwt:
    header: authorization
    secret: ${SECRET_KEY}
    access-token-validity-in-seconds: 5400
    refresh-token-validity-in-seconds: 604800

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://catxi-university-taxi-b0936.web.app/callback/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,account_email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20    # 기존 8 → 20 (FCM 배치 처리 최적화)
          max-idle: 20      # 기존 8 → 20 (유휴 연결 확보)
          min-idle: 5       # 기존 0 → 5 (최소 연결 유지)
          max-wait: 3000ms  # 연결 대기 시간 설정

  jackson:
    time-zone: Asia/Seoul

fcm:
  service-account-file: ${FCM_SERVICE_ACCOUNT_FILE:}

server:
  port: 8080

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.web.client: WARN
    com.project.catxi: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p %t --- [%15.15t] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p %t --- [%15.15t] %-40.40logger{39} : %m%n"
  file:
    name: /app/logs/catxi-backend-prod.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 5
      total-size-cap: 300MB