spring:

  datasource:
    url: jdbc:mysql://${HOST}:${PORT}/catxi?allowPublicKeyRetrieval=true&useSSL=false
    username: ${USER}
    password: ${PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    header: authorization
    secret: ${SECRET_KEY}
    access-token-validity-in-seconds: 3600

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/auth/login/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,account_email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # Redis 설정 추가 (로컬용)
  data:
    redis:
      host: ${REDIS_HOST:localhost}      # 기본값 localhost
      port: ${REDIS_PORT:6379}           # 기본값 6379
      password: ${REDIS_PW:}             # 기본값 빈 문자열 (비밀번호 없음)
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8080

# WebSocket 설정 추가
websocket:
  endpoint: "/ws"
  allowed-origins: "*"

# Redis Pub/Sub 채널 설정 추가
chat:
  redis:
    channels:
      message: "chatMessage"
      join: "roomJoin"
      exit: "roomExit"
