---
plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-2

keyed_groups:
  - key: tags.Name
    prefix: ""
  - key: tags.Role | default('')
    prefix: tag_Role_
    separator: "_"

compose:
  ansible_host: public_ip_address