---
- name: Deploy Catxi Backend Application
  hosts: tag_Role__app
  become: yes
  serial: 1
  max_fail_percentage: 0
  vars:
    app_port: 8080
    health_check_timeout: 300

  pre_tasks:
    - name: Debug received variables from AWX
      debug:
        msg:
          - "=== AWX Variables Debug ==="
          - "docker_image: '{{ docker_image | default('UNDEFINED') }}'"
          - "docker_registry_username: '{{ docker_registry_username | default('UNDEFINED') }}'"
          - "build_number: '{{ build_number | default('UNDEFINED') }}'"
          - "git_branch: '{{ git_branch | default('UNDEFINED') }}'"

    - name: Set deployment variables with fallbacks
      set_fact:
        final_docker_image: "{{ docker_image | default('xms1228/catxi-backend:latest') }}"
        final_docker_registry_username: "{{ docker_registry_username | default('') }}"
        final_docker_registry_password: "{{ docker_registry_password | default('') }}"
        final_docker_registry_url: "{{ docker_registry_url | default('https://index.docker.io/v1/') }}"
        final_build_number: "{{ build_number | default('unknown') }}"
        final_git_branch: "{{ git_branch | default('unknown') }}"

    - name: Display final deployment information
      debug:
        msg:
          - "=== Final Deployment Variables ==="
          - "Deploying to: {{ inventory_hostname }}"
          - "Docker Image: {{ final_docker_image }}"
          - "Build Number: {{ final_build_number }}"
          - "Git Branch: {{ final_git_branch }}"

  tasks:
    - name: Create application directory
      file:
        path: /opt/catxi
        state: directory
        mode: '0755'

    - name: Copy existing docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /opt/catxi/docker-compose.yml
        mode: '0644'

    - name: Create environment file with variables
      template:
        src: templates/env.j2
        dest: /opt/catxi/.env
        mode: '0600'

    - name: Stop existing containers
      community.docker.docker_compose_v2:
        project_src: /opt/catxi
        state: absent
      ignore_errors: yes

    - name: Login to Docker Registry (if credentials provided)
      docker_login:
        username: "{{ final_docker_registry_username }}"
        password: "{{ final_docker_registry_password }}"
        registry_url: "{{ final_docker_registry_url }}"
      when:
        - final_docker_registry_username != ""
        - final_docker_registry_password != ""

    - name: Pull Docker image
      docker_image:
        name: "{{ final_docker_image }}"
        source: pull
        force_source: yes
      register: pull_result
      retries: 3
      delay: 10

    - name: Deploy with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/catxi
        state: present
        recreate: always

    - name: Wait for container to start
      pause:
        seconds: 45  # 더 긴 시간 대기

    - name: Check if container is running
      shell: docker ps --format "table {{.Names}}\t{{.Status}}" | grep catxi-backend || echo "Container not found"
      register: container_status
      ignore_errors: yes

    - name: Display container status
      debug:
        msg: "Container status: {{ container_status.stdout }}"

    - name: Simple health check (optional)
      uri:
        url: "http://{{ ansible_host | default(ansible_default_ipv4.address) }}:{{ app_port }}/actuator/health"
        method: GET
        timeout: 5
      register: simple_health
      ignore_errors: yes
      delegate_to: localhost
      become: no

    - name: Display health check result
      debug:
        msg: "Health check result: {{ 'SUCCESS' if simple_health.status == 200 else 'FAILED - but deployment may still be working' }}"

    - name: Verify deployment success
      debug:
        msg: "✅ Deployment completed on {{ inventory_hostname }} with image {{ final_docker_image }}"

    - name: Clean up old Docker images
      shell: docker image prune -af
      ignore_errors: yes

  post_tasks:
    - name: Pause between server deployments
      pause:
        seconds: 30
      when: inventory_hostname != ansible_play_hosts[-1]