---
- name: Deploy Catxi Backend Application
  hosts: tag_Role__app
  become: yes
  serial: 1
  max_fail_percentage: 0
  vars:
    app_port: 8080
    health_check_timeout: 300

  pre_tasks:
    - name: Debug received variables from AWX
      debug:
        msg:
          - "=== AWX Variables Debug ==="
          - "docker_image: '{{ docker_image | default('UNDEFINED') }}'"
          - "docker_registry_username: '{{ docker_registry_username | default('UNDEFINED') }}'"
          - "build_number: '{{ build_number | default('UNDEFINED') }}'"
          - "git_branch: '{{ git_branch | default('UNDEFINED') }}'"

    - name: Set deployment variables with fallbacks
      set_fact:
        final_docker_image: "{{ docker_image | default('xms1228/catxi-backend:latest') }}"
        final_docker_registry_username: "{{ docker_registry_username | default('') }}"
        final_docker_registry_password: "{{ docker_registry_password | default('') }}"
        final_docker_registry_url: "{{ docker_registry_url | default('https://index.docker.io/v1/') }}"
        final_build_number: "{{ build_number | default('unknown') }}"
        final_git_branch: "{{ git_branch | default('unknown') }}"

    - name: Display final deployment information
      debug:
        msg:
          - "=== Final Deployment Variables ==="
          - "Deploying to: {{ inventory_hostname }}"
          - "Docker Image: {{ final_docker_image }}"
          - "Build Number: {{ final_build_number }}"
          - "Git Branch: {{ final_git_branch }}"

  tasks:
    - name: Create application directory
      file:
        path: /opt/catxi
        state: directory
        mode: '0755'

    - name: Create config directory for FCM
      file:
        path: /opt/catxi/config
        state: directory
        mode: '0755'

    - name: Copy existing docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /opt/catxi/docker-compose.yml
        mode: '0644'

    - name: Create environment file with variables
      template:
        src: templates/env.j2
        dest: /opt/catxi/.env
        mode: '0600'

    - name: Create FCM service account file
      copy:
        content: "{{ lookup('env', 'FCM_SERVICE_ACCOUNT_FILE') }}"
        dest: /opt/catxi/config/fcm-service-account.json
        mode: '0644'
      when: lookup('env', 'FCM_SERVICE_ACCOUNT_FILE') != ""

    - name: Stop existing containers
      community.docker.docker_compose_v2:
        project_src: /opt/catxi
        state: absent
      ignore_errors: yes

    - name: Login to Docker Registry (if credentials provided)
      docker_login:
        username: "{{ final_docker_registry_username }}"
        password: "{{ final_docker_registry_password }}"
        registry_url: "{{ final_docker_registry_url }}"
      when:
        - final_docker_registry_username != ""
        - final_docker_registry_password != ""

    - name: Pull Docker image
      docker_image:
        name: "{{ final_docker_image }}"
        source: pull
        force_source: yes
      register: pull_result
      retries: 3
      delay: 10

    - name: Deploy with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/catxi
        state: present
        recreate: always

    - name: Wait for container to start
      pause:
        seconds: 30

    - name: Wait for application to be ready
      shell: curl -f http://localhost:{{ app_port }}/actuator/health
      register: health_check
      until: health_check.rc == 0
      retries: 20
      delay: 2

    - name: Verify deployment success
      debug:
        msg: "✅ App is Healthy"

    - name: Clean up old Docker images
      shell: docker image prune -af
      ignore_errors: yes

  post_tasks:
    - name: Pause between server deployments
      pause:
        seconds: 15
      when: inventory_hostname != ansible_play_hosts[-1]
